In [1]:
import torch
torch.__version__

'2.5.0.dev20240613'

In [3]:
device = None

dir(torch.backends)

['ContextProp',
 'PropModule',
 '__allow_nonbracketed_mutation',
 '__allow_nonbracketed_mutation_flag',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'contextmanager',
 'cpu',
 'cuda',
 'cudnn',
 'disable_global_flags',
 'flags_frozen',
 'mha',
 'mkl',
 'mkldnn',
 'mps',
 'nnpack',
 'openmp',
 'quantized',
 'types']

In [5]:
dir(torch.cuda)

['Any',
 'BFloat16Storage',
 'BFloat16Tensor',
 'BoolStorage',
 'BoolTensor',
 'ByteStorage',
 'ByteTensor',
 'CUDAGraph',
 'CUDAPluggableAllocator',
 'Callable',
 'CharStorage',
 'CharTensor',
 'ComplexDoubleStorage',
 'ComplexFloatStorage',
 'CudaError',
 'DeferredCudaCallError',
 'Device',
 'DoubleStorage',
 'DoubleTensor',
 'Event',
 'ExternalStream',
 'FloatStorage',
 'FloatTensor',
 'HalfStorage',
 'HalfTensor',
 'IntStorage',
 'IntTensor',
 'List',
 'LongStorage',
 'LongTensor',
 'Optional',
 'OutOfMemoryError',
 'ShortStorage',
 'ShortTensor',
 'Stream',
 'StreamContext',
 'Tuple',
 'Union',
 '_CudaBase',
 '_CudaDeviceProperties',
 '_DeviceGuard',
 '_HAS_PYNVML',
 '_LazySeedTracker',
 '_PYNVML_ERR',
 '_WrappedTritonKernel',
 '__all__',
 '__annotations__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_cached_device_count',
 '_check_bf16_tensor_supported',
 '_check_capability',
 '_check_cubins',
 

In [10]:
print(dir(torch.backends.cuda))
torch.cuda.is_available()

['SDPAParams', 'SDPBackend', 'Union', '_BlasBackends', '_BlasBackends_str', '_LinalgBackends', '_LinalgBackends_str', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'can_use_efficient_attention', 'can_use_flash_attention', 'contextlib', 'cuBLASModule', 'cuFFTPlanCache', 'cuFFTPlanCacheAttrContextProp', 'cuFFTPlanCacheManager', 'cudnn_sdp_enabled', 'cufft_plan_cache', 'deprecated', 'enable_cudnn_sdp', 'enable_flash_sdp', 'enable_math_sdp', 'enable_mem_efficient_sdp', 'flash_sdp_enabled', 'is_built', 'math_sdp_enabled', 'matmul', 'mem_efficient_sdp_enabled', 'preferred_blas_library', 'preferred_linalg_library', 'sdp_kernel', 'torch']


False

In [7]:
dir(torch.mps)

['Event',
 'Tensor',
 'Union',
 '__all__',
 '__annotations__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_default_mps_generator',
 '_get_default_mps_generator',
 '_is_in_bad_fork',
 'current_allocated_memory',
 'device_count',
 'driver_allocated_memory',
 'empty_cache',
 'event',
 'get_rng_state',
 'manual_seed',
 'profiler',
 'recommended_max_memory',
 'seed',
 'set_per_process_memory_fraction',
 'set_rng_state',
 'synchronize',
 'torch']

In [11]:
print(dir(torch.backends.mps))
print(torch.backends.mps.is_available())
torch.mps.device_count()

['Optional', '_Library', '__all__', '__annotations__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_init', '_lib', '_lru_cache', 'is_available', 'is_built', 'is_macos13_or_newer', 'is_macos_or_newer', 'torch']
True


1

In [12]:
import numpy as np
np.__version__


'1.26.4'

In [20]:
lst = [0,1,2,3,4]
arr = np.array(lst)
print(arr, arr.dtype)


[0 1 2 3 4] int64


In [21]:
# Both numpy and tensor use same memory so if we update on other also get updated
tensors = torch.from_numpy(arr)
print(tensors, tensors.dtype)

tensor([0, 1, 2, 3, 4]) torch.int64


In [22]:
print(tensors[:2])
print(tensors[1:4])
print(tensors[2])
tensors[1] = 100
print(tensors)
print(arr)

tensor([0, 1])
tensor([1, 2, 3])
tensor(2)
tensor([  0, 100,   2,   3,   4])
[  0 100   2   3   4]


In [23]:
# for saperate numpy and tensor memory
tensors = torch.tensor(arr)
print(tensors)
print(arr)
tensors[2] = 300
print(tensors)
print(arr)

tensor([  0, 100,   2,   3,   4])
[  0 100   2   3   4]
tensor([  0, 100, 300,   3,   4])
[  0 100   2   3   4]


In [25]:
zeros = torch.zeros(2,3, dtype=torch.float32)
ones = torch.ones(2,3, dtype=torch.float64)
print(zeros, zeros.dtype)
print(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [29]:
t1 = torch.tensor([2,3,4], dtype=torch.float)
t2 = torch.tensor([10,200,3000], dtype=torch.float)

print(t2+t1)
print(torch.add(t1, t2))

t3 = torch.zeros(3, dtype=torch.float)
print(torch.add(t1, t2, out=t3))
print(t3, t3.dtype)


tensor([  12.,  203., 3004.])
tensor([  12.,  203., 3004.])
tensor([  12.,  203., 3004.])
tensor([  12.,  203., 3004.]) torch.float32
