In [5]:
import torch

device = "cpu"

if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    torch.device("cpu")


In [7]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], device=device, dtype=torch.float32, requires_grad=False)

In [8]:
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='mps:0')

In [9]:
my_tensor.device

device(type='mps', index=0)

In [10]:
my_tensor.requires_grad

False

In [11]:
my_tensor.shape

torch.Size([2, 3])

In [12]:
x = torch.empty((2,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
x = torch.zeros((2,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
x = torch.rand((2,3))
x

tensor([[0.8195, 0.8555, 0.6982],
        [0.6499, 0.5226, 0.6449]])

In [15]:
x = torch.ones((3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
x = torch.eye(3,3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [18]:
x = torch.arange(start=0,end=10, step=2)
x

tensor([0, 2, 4, 6, 8])

In [19]:
x = torch.linspace(start=.1, end=1, steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [20]:
x = torch.empty((1,5)).normal_(mean=0, std=1)
x

tensor([[-0.8426, -0.0074, -0.5371,  1.2589, -2.9709]])

In [21]:
x = torch.empty((1,5)).uniform_(0,1)
x

tensor([[0.6421, 0.4013, 0.0535, 0.2919, 0.8344]])

In [22]:
x = torch.diag(torch.ones(3))
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [24]:
t = torch.arange(4)
print(t)
t.bool()


tensor([0, 1, 2, 3])


tensor([False,  True,  True,  True])

In [26]:
import numpy as np

arr = np.zeros((3,3))
t = torch.from_numpy(arr)
t

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [27]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

In [31]:
z = torch.zeros(3)
print(z)
torch.add(x, y, out=z)
z

tensor([0., 0., 0.])


tensor([5., 7., 9.])

In [32]:
z = torch.add(x,y)
z

tensor([5, 7, 9])

In [34]:
z = x+y
z

tensor([5, 7, 9])

In [35]:
z = x-y
z

tensor([-3, -3, -3])

In [38]:
z = y/x
z

tensor([4.0000, 2.5000, 2.0000])

In [39]:
x.pow(2)

tensor([1, 4, 9])

In [40]:
z = x**3
z

tensor([ 1,  8, 27])

In [41]:
z = x > 1
z

tensor([False,  True,  True])

In [42]:
z= x*y
z

tensor([ 4, 10, 18])

In [44]:
z= x @ y
z

tensor(32)

In [45]:
batch = 32
n = 10
m = 20
p = 30
# batch multiplication
t1 = torch.rand((batch, n,m))
t2 = torch.rand((batch, m,p))
t = torch.bmm(t1, t2)


In [47]:
# broadcasting
x = torch.ones((5,5))
y = torch.rand((1,5))

z = x-y
z

tensor([[0.1782, 0.4004, 0.1989, 0.8930, 0.7684],
        [0.1782, 0.4004, 0.1989, 0.8930, 0.7684],
        [0.1782, 0.4004, 0.1989, 0.8930, 0.7684],
        [0.1782, 0.4004, 0.1989, 0.8930, 0.7684],
        [0.1782, 0.4004, 0.1989, 0.8930, 0.7684]])

In [53]:
x = torch.tensor([[1,10,100], [4,5,6]])
print(x)
print(x.shape)
sum_x = torch.sum(x, dim=0)
sum_x

tensor([[  1,  10, 100],
        [  4,   5,   6]])
torch.Size([2, 3])


tensor([  5,  15, 106])

In [54]:
sum_x = torch.sum(x, dim=1)
sum_x

tensor([111,  15])

In [55]:
values, indices = torch.max(x, dim=0)
print(values, indices)
values, indices = torch.max(x, dim=1)
print(values, indices)

tensor([  4,  10, 100]) tensor([1, 0, 0])
tensor([100,   6]) tensor([2, 2])


In [56]:
abs_x = torch.abs(x)
abs_x

tensor([[  1,  10, 100],
        [  4,   5,   6]])

In [57]:
torch.argmax(x, dim=0)

tensor([1, 0, 0])

In [58]:
torch.argmin(x, dim=0)

tensor([0, 1, 1])

In [59]:
mean_x = torch.mean(x.float(), dim=0)
mean_x

tensor([ 2.5000,  7.5000, 53.0000])

In [61]:
#torch.eq(x,y)

In [63]:
y = torch.tensor([4,5,6])
sorted_y, indices = torch.sort(y, dim=0, descending=True)
print(sorted_y, indices)

tensor([6, 5, 4]) tensor([2, 1, 0])


In [64]:
z = torch.clamp(x, min=5, max=20)
z

tensor([[ 5, 10, 20],
        [ 5,  5,  6]])

In [74]:
# indexing in tensor

batch_size = 2
features = 3
x = torch.rand((batch_size, features))
x

tensor([[0.3382, 0.5575, 0.2514],
        [0.2095, 0.6836, 0.5697]])

In [75]:
x[0]

tensor([0.3382, 0.5575, 0.2514])

In [76]:
x[0]

tensor([0.3382, 0.5575, 0.2514])

In [77]:
x[0,:]

tensor([0.3382, 0.5575, 0.2514])

In [78]:
x[:,0]

tensor([0.3382, 0.2095])

In [80]:
x[0, 0:2]

tensor([0.3382, 0.5575])

In [81]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
indices = [2,4,5]
x[indices]

tensor([2, 4, 5])

In [83]:
x = torch.arange(9)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [84]:
x.view((3,3))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [85]:
x.reshape((3,3))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [87]:
x.reshape((3,3)).t()

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [89]:
x = torch.rand((2,5))
y = torch.rand((2,5))
torch.cat((x,y), dim=0).shape

torch.Size([4, 5])

In [90]:
torch.cat((x,y), dim=1).shape

torch.Size([2, 10])

In [91]:
batch = 64
x = torch.rand((batch, 2,4))
z = x.view(batch, -1)
z.shape

torch.Size([64, 8])

In [93]:
z = x.permute(0, 2,1)
z.shape

torch.Size([64, 4, 2])

In [94]:
x = torch.arange(10)
x.shape

torch.Size([10])

In [96]:
x.unsqueeze(0).shape

torch.Size([1, 10])

In [97]:
x.unsqueeze(1).shape

torch.Size([10, 1])

In [98]:
x.unsqueeze(0).unsqueeze(1).shape

torch.Size([1, 1, 10])